import {IQuestionAnswer} from "../../app/models/QuestionAnswer.model";

export class QuestionAnswerSeed {
  static questionAnswerSeed: IQuestionAnswer[][] =
    [[
      {question: 'Podaj przykład czegoś co można znaleźć w garażu',
      answer: [
        {answer: 'Samochód', points: 44, active: false},
        {answer: 'Narzędzia', points: 31, active: false},
        {answer: 'Kosiarka', points: 26, active: false},
        {answer: 'Rower', points: 13, active: false},
        {answer: 'Śmietniki', points: 8, active: false},
      ],
      multiplier: 1},
      {question: 'Podaj przykład czegoś co zmienia kolor',
        answer: [
          {answer: 'Kameleon', points: 48, active: false},
          {answer: 'Jaszczurka', points: 39, active: false},
          {answer: 'Niebo', points: 26, active: false},
          {answer: 'Włosy', points: 14, active: false},
          {answer: 'Liście', points: 9, active: false},
        ],
        multiplier: 1},
      {question: 'Wymień coś do czego można dodać cukier',
        answer: [
          {answer: 'Herbata', points: 32, active: false},
          {answer: 'Kawa', points: 28, active: false},
          {answer: 'Ciasto', points: 19, active: false},
          {answer: 'Truskawki', points: 14, active: false},
          {answer: 'Napój', points: 9, active: false},
        ],
        multiplier: 1},
      {question: 'Wymień coś na co dzieci zawsze narzekają',
        answer: [
          {answer: 'Praca domowa', points: 37, active: false},
          {answer: 'Chodzenie do szkoły', points: 26, active: false},
          {answer: 'Obowiązki domowe', points: 19, active: false},
          {answer: 'Pora do spania', points: 16, active: false},
          {answer: 'Głód', points: 7, active: false},
        ],
        multiplier: 2},
      {question: 'Co można kupić używne',
        answer: [
          {answer: 'Samochód', points: 51, active: false},
          {answer: 'Ubrania', points: 47, active: false},
          {answer: 'Meble', points: 30, active: false},
          {answer: 'Ksiązki', points: 23, active: false},
          {answer: 'Elektronika', points: 13, active: false},
        ],
        multiplier: 3},
    ],
      [
        {question: 'Czym można poplamić ubranie',
          answer: [
            {answer: 'Wino', points: 39, active: false},
            {answer: 'Trawa', points: 28, active: false},
            {answer: 'Krew', points: 16, active: false},
            {answer: 'Brud', points: 13, active: false},
            {answer: 'Olej', points: 6, active: false},
          ],
          multiplier: 1},
        {question: 'Podaj przykład czegoś czego ludzie się boją',
          answer: [
            {answer: 'Pająki', points: 46, active: false},
            {answer: 'Ciemność', points: 41, active: false},
            {answer: 'Węże', points: 35, active: false},
            {answer: 'Duchy', points: 22, active: false},
            {answer: 'Wysokość', points: 13, active: false},
          ],
          multiplier: 1},
        {question: 'Co zakładamy do spania',
          answer: [
            {answer: 'Piżama', points: 51, active: false},
            {answer: 'Bielizna', points: 48, active: false},
            {answer: 'Koszula nocna', points: 31, active: false},
            {answer: 'Skarpety', points: 20, active: false},
            {answer: 'Koszulkę', points: 13, active: false},
          ],
          multiplier: 1},
        {question: 'Wymień coś czego nie można by było robić bez ust?',
          answer: [
            {answer: 'Jeść', points: 53, active: false},
            {answer: 'Pić', points: 46, active: false},
            {answer: 'Całować', points: 30, active: false},
            {answer: 'Rozmawiać', points: 21, active: false},
            {answer: 'Gwizdać', points: 11, active: false},
          ],
          multiplier: 2},
        {question: 'Co można powiesić na ścianie',
          answer: [
            {answer: 'Zdjęcie', points: 31, active: false},
            {answer: 'Telewizor', points: 29, active: false},
            {answer: 'Lustro', points: 23, active: false},
            {answer: 'Obraz', points: 17, active: false},
            {answer: 'Zegar', points: 10, active: false},
          ],
          multiplier: 3},
      ],
      [
        {question: 'Podaj przykład czegoś co traci ważność',
          answer: [
            {answer: 'Mleko', points: 51, active: false},
            {answer: 'Mięso', points: 47, active: false},
            {answer: 'Bilet parkingowy', points: 33, active: false},
            {answer: 'Prawo jazdy', points: 21, active: false},
            {answer: 'Karta bankowa', points: 14, active: false},
          ],
          multiplier: 1},
        {question: 'Co można zastosować na ból głowy',
          answer: [
            {answer: 'Tabletki przeciwbólowe', points: 47, active: false},
            {answer: 'Paracetamol', points: 39, active: false},
            {answer: 'Kawa', points: 21, active: false},
            {answer: 'Herbata', points: 16, active: false},
            {answer: 'Drzemka', points: 11, active: false},
          ],
          multiplier: 1},
        {question: 'Co robimy gdy nie możemy zasnąć',
          answer: [
            {answer: 'Czytamy', points: 32, active: false},
            {answer: 'Oglądamy telewizje', points: 28, active: false},
            {answer: 'Liczymy owce', points: 21, active: false},
            {answer: 'Jemy', points: 19, active: false},
            {answer: 'Pijemy mleko', points: 7, active: false},
          ],
          multiplier: 1},
        {question: 'Co jemy w czasie świąt bożonarodzeniowych',
          answer: [
            {answer: 'Bigos', points: 39, active: false},
            {answer: 'Barszcz czerwony', points: 31, active: false},
            {answer: 'Karp', points: 26, active: false},
            {answer: 'Pierogi', points: 17, active: false},
            {answer: 'Sernik', points: 10, active: false},
          ],
          multiplier: 2},
        {question: 'Co porusza się bardzo powoli',
          answer: [
            {answer: 'Ślimak', points: 44, active: false},
            {answer: 'Żółw', points: 42, active: false},
            {answer: 'Leniwiec', points: 21, active: false},
            {answer: 'Starsi ludzie', points: 16, active: false},
            {answer: 'dziecko', points: 6, active: false},
          ],
          multiplier: 3},
      ],
      [
        {question: 'Wymień składniki sałatki owocowej',
          answer: [
            {answer: 'Truskawki', points: 41, active: false},
            {answer: 'Winogrona', points: 38, active: false},
            {answer: 'Jabłka', points: 29, active: false},
            {answer: 'Brzoskwinie', points: 16, active: false},
            {answer: 'Ananas', points: 10, active: false},
          ],
          multiplier: 1},
        {question: 'Wymień miejsce w których można pływać',
          answer: [
            {answer: 'Morze', points: 39, active: false},
            {answer: 'Basen', points: 32, active: false},
            {answer: 'Jezioro', points: 25, active: false},
            {answer: 'Ocean', points: 13, active: false},
            {answer: 'Rzeka', points: 9, active: false},
          ],
          multiplier: 1},
        {question: 'Czym można jeść',
          answer: [
            {answer: 'Rękami', points: 49, active: false},
            {answer: 'Widelec', points: 43, active: false},
            {answer: 'Łyżka', points: 33, active: false},
            {answer: 'Nóż', points: 21, active: false},
            {answer: 'Talerz', points: 14, active: false},
          ],
          multiplier: 1},
        {question: 'Czego pieniądze nie mogą kupić',
          answer: [
            {answer: 'Miłości', points: 51, active: false},
            {answer: 'Szczęście', points: 42, active: false},
            {answer: 'Zdrowie', points: 37, active: false},
            {answer: 'Zaufanie', points: 21, active: false},
            {answer: 'Szacunek', points: 9, active: false},
          ],
          multiplier: 2},
        {question: 'Co można nosić na stopach',
          answer: [
            {answer: 'Buty', points: 40, active: false},
            {answer: 'Skarpety', points: 37, active: false},
            {answer: 'Obuwie sportowe', points: 29, active: false},
            {answer: 'Kozaki', points: 15, active: false},
            {answer: 'Trzewiki', points: 9, active: false},
          ],
          multiplier: 3},
      ],
      [
        {question: 'Najlepsze miejsce do picia to',
          answer: [
            {answer: 'Polanka', points: 41, active: false},
            {answer: 'Karczma u chlopa', points: 38, active: false},
            {answer: 'Piwnica', points: 29, active: false},
            {answer: 'Dzialka u Danielka', points: 16, active: false},
            {answer: 'Basen', points: 10, active: false},
          ],
          multiplier: 1},
        {question: 'Najczesciej uzywana ksywa Daniela',
          answer: [
            {answer: 'Gej', points: 39, active: false},
            {answer: 'Serek', points: 32, active: false},
            {answer: 'Danielson', points: 25, active: false},
            {answer: 'Danielek', points: 13, active: false},
            {answer: 'Gejoza', points: 9, active: false},
          ],
          multiplier: 1},
        {question: 'Można',
          answer: [
            {answer: '100', points: 49, active: false},
            {answer: '90', points: 43, active: false},
            {answer: '80', points: 33, active: false},
            {answer: '70', points: 21, active: false},
            {answer: '50', points: 14, active: false},
          ],
          multiplier: 2},
        {question: 'Litera alfabeta',
          answer: [
            {answer: 'A', points: 51, active: false},
            {answer: 'Z', points: 42, active: false},
            {answer: '', points: 37, active: false},
            {answer: 'D', points: 21, active: false},
            {answer: 'E', points: 9, active: false},
          ],
          multiplier: 3},
        {question: 'Co to',
          answer: [
            {answer: 'Kanapka', points: 40, active: false},
            {answer: 'Jajo', points: 37, active: false},
            {answer: 'Cosam', points: 29, active: false},
            {answer: 'ASd', points: 15, active: false},
            {answer: 'wwww', points: 9, active: false},
          ],
          multiplier: 4},
      ],
    ]
}
